/**
 * This file contains structured fingering chart data.
 * This data is used to ground the AI model and for the interactive fingering tool.
 */

/*
Legend and notation:
- Woodwinds grouped as: [Thumb/Keys] | LH 1-3 | RH 1-3 | Pinky/Side/Aux
  Symbols:
    X = pressed/covered, O = open
    OCT = octave (sax/oboe), R = register (clarinet), T = thumb hole (clarinet/oboe)
    H = half-hole (oboe)
    G# / F# / Eb / Side-Bb etc. indicate dedicated keys/side keys
    Lp/Rp = left/right pinky cluster (clarinet)
- Brass (valves): digits indicate valves; 0 = open
- Trombone (slide): positions 1 (shortest) to 7 (longest). Some notes allow “1 or 6” etc.
Ranges target practical school band repertoire; extreme altissimo omitted.
Alternates included where they are commonly taught for technique or intonation.
Security note: No external APIs or keys used.
*/

export const INSTRUMENT_DATA = [
  // ========== FLUTE (W21FL) ==========
  {
    name: "Flute",
    category: "Woodwind",
    notation_key:
      "X = Key Pressed, O = Open. Groups: Thumb | LH 1-3 | RH 1-3 | RH Pinky (Eb key).",
    hands_layout: ["Thumb", "Left Hand", "Right Hand", "Pinky/Aux"],
    care_and_technique: [
        { title: "Daily Swabbing", description: "After each playing session, use a silk or microfiber swab to clean the moisture from inside all three sections of your flute. This prevents pad damage and keeps the instrument clean." },
        { title: "Headjoint Alignment", description: "Align the embouchure hole on the headjoint with the first key on the body. This is a good starting point, but you can adjust slightly for comfort and tuning." },
        { title: "Embouchure Focus", description: "Practice making a focused, steady airstream. Think of saying the word 'poo' or 'too'. Aim for a clear, beautiful tone on long tones before playing fast passages." },
    ],
    notes: [
      { note: "C4", fingering: "X | X X X | X X X | X", alternates: [] },
      { note: "C#4/Db4", fingering: "X | X X X | X X X | O", alternates: [] },
      { note: "D4", fingering: "X | X X X | X X O | X", alternates: [] },
      { note: "D#4/Eb4", fingering: "X | X X X | X O O | X", alternates: [] },
      { note: "E4", fingering: "X | X X X | O O O | X", alternates: [] },
      { note: "F4", fingering: "X | X X O | O O O | X", alternates: [] },
      { note: "F#4/Gb4", fingering: "X | X O O | O O O | O", alternates: [] },
      { note: "G4", fingering: "X | O O O | O O O | O", alternates: [] },
      { note: "G#4/Ab4", fingering: "X | O O O | X X X | G#", alternates: [] },
      { note: "A4", fingering: "O | X X O | O O O | O", alternates: [] },
      { note: "A#4/Bb4", fingering: "O | X O X | O O O | O", alternates: ["O | X X O | O O O | X"] },
      { note: "B4", fingering: "O | X O O | O O O | O", alternates: [] },
      { note: "C5", fingering: "O | O X O | O O O | O", alternates: [] },
      { note: "C#5/Db5", fingering: "O | O O O | O O O | O", alternates: [] },
      { note: "D5", fingering: "X | X X O | X X O | X", alternates: [] },
      { note: "D#5/Eb5", fingering: "X | X X X | X O O | X", alternates: [] },
      { note: "E5", fingering: "X | X X X | O O O | X", alternates: [] },
      { note: "F5", fingering: "X | X X O | O O O | X", alternates: [] },
      { note: "F#5/Gb5", fingering: "X | X O O | O O O | O", alternates: [] },
      { note: "G5", fingering: "X | O O O | O O O | O", alternates: [] },
      { note: "G#5/Ab5", fingering: "O | X X O | X X X | G#", alternates: [] },
      { note: "A5", fingering: "O | X X O | X O O | O", alternates: ["O | X X O | O X O | O"] },
      { note: "A#5/Bb5", fingering: "O | X O X | O O O | O", alternates: [] },
      { note: "B5", fingering: "X | X O O | X O O | O", alternates: [] },
      { note: "C6", fingering: "O | X O O | O O O | O", alternates: [] },
    ],
  },

  // ========== OBOE (W21OB) ==========
  {
    name: "Oboe",
    category: "Woodwind",
    notation_key:
      "X = Pressed/Covered, O = Open, H = Half-hole, OCT = octave. Groups: OCT/T | LH 1-3 | RH 1-3 | Pinky/Aux.",
    hands_layout: ["Octave/Thumb", "Left Hand", "Right Hand", "Pinky/Aux"],
    care_and_technique: [
        { title: "Reed Care is Critical", description: "Always soak your reed in water for a minute before playing. Store reeds in a proper reed case to let them dry evenly and prevent warping or mold." },
        { title: "Swab Gently", description: "Use a feather or soft pull-through swab after playing. Be extremely careful not to snag the swab on the delicate octave key pips inside the top joint." },
        { title: "Support the Weight", description: "Use a neck strap or thumb rest cushion to avoid straining your right hand. Good posture is key to supporting the instrument's weight and for proper breath support." },
    ],
    notes: [
        { note: "A#3/Bb3", fingering: "O-O | X X X | X X X | Bb", alternates: [] },
        { note: "B3", fingering: "O-O | X X X | X X X | B", alternates: [] },
        { note: "C4", fingering: "O-O | X X X | X X X | C", alternates: [] },
        { note: "C#4/Db4", fingering: "O-O | X X X | X X X | C#", alternates: [] },
        { note: "D4", fingering: "O-O | X X X | X X X | O", alternates: [] },
        { note: "D#4/Eb4", fingering: "O-O | X X X | X X X | Eb", alternates: [] },
        { note: "E4", fingering: "O-O | X X X | X X O | O", alternates: [] },
        { note: "F4", fingering: "O-O | X X X | X O O | O", alternates: ["O-O | X X X | X O X | F"] },
        { note: "F#4/Gb4", fingering: "O-O | X X X | O X O | O", alternates: [] },
        { note: "G4", fingering: "O-O | X X X | O O O | O", alternates: [] },
        { note: "G#4/Ab4", fingering: "O-O | X X O | X X X | G#", alternates: [] },
        { note: "A4", fingering: "O-O | X X O | O O O | O", alternates: [] },
        { note: "A#4/Bb4", fingering: "O-O | X O X | O O O | O", alternates: [] },
        { note: "B4", fingering: "O-O | X O O | O O O | O", alternates: [] },
        { note: "C5", fingering: "H-O | X X O | O O O | O", alternates: [] },
        { note: "C#5/Db5", fingering: "H-O | O X O | O O O | O", alternates: [] },
        { note: "D5", fingering: "OCT-O | X X X | X X X | O", alternates: [] },
        { note: "D#5/Eb5", fingering: "OCT-O | X X X | X X X | Eb", alternates: [] },
        { note: "E5", fingering: "OCT-O | X X X | X X O | O", alternates: [] },
        { note: "F5", fingering: "OCT-O | X X X | X O O | O", alternates: ["OCT-O | X X X | X O X | F"] },
        { note: "F#5/Gb5", fingering: "OCT-O | X X X | O X O | O", alternates: [] },
        { note: "G5", fingering: "OCT-O | X X X | O O O | O", alternates: [] },
        { note: "G#5/Ab5", fingering: "OCT-O | X X O | X X X | G#", alternates: [] },
        { note: "A5", fingering: "OCT-O | X X O | O O O | O", alternates: [] },
        { note: "A#5/Bb5", fingering: "OCT-O | X O X | O O O | O", alternates: [] },
        { note: "B5", fingering: "OCT-O | X O O | O O O | O", alternates: [] },
        { note: "C6", fingering: "OCT-O | O X O | O O O | O", alternates: [] },
    ],
  },
  
  // ========== B♭ CLARINET (W21CL) ==========
  {
    name: "B-flat Clarinet",
    category: "Woodwind",
    notation_key:
      "X = Covered, O = Open, T = LH thumb hole, R = Register key. Groups: R-T | LH 1-3 | RH 1-3.",
    hands_layout: ["Keys/Thumb", "Left Hand", "Right Hand"],
    care_and_technique: [
        { title: "Reed Positioning", description: "Align the tip of the reed with the tip of the mouthpiece. A tiny sliver of the mouthpiece should be visible above the reed. Secure it firmly with the ligature." },
        { title: "Swab Every Time", description: "Moisture can ruin pads and cause the wood to swell. Use a pull-through swab to clean the inside of your clarinet from the bell to the barrel after every session." },
        { title: "Cork Grease", description: "Apply a small amount of cork grease to the tenon corks when assembling the instrument if it feels tight. This prevents damage to the corks." },
        { title: "Crossing the Break", description: "Practice scales and arpeggios that go from the lower register (e.g., A or B-flat) to the upper register (e.g., B or C) smoothly. Focus on maintaining consistent air support." },
    ],
    notes: [
        { note: "E3", fingering: "O-T | X X X | X X X", alternates: [] },
        { note: "F3", fingering: "O-T | X X X | X X O", alternates: [] },
        { note: "F#3/Gb3", fingering: "O-T | X X X | X O O", alternates: [] },
        { note: "G3", fingering: "O-T | X X X | O O O", alternates: [] },
        { note: "G#3/Ab3", fingering: "O-T | X X O | X X X", alternates: [] },
        { note: "A3", fingering: "O-T | X X O | O O O", alternates: [] },
        { note: "A#3/Bb3", fingering: "O-T | X O O | O O O", alternates: [] },
        { note: "B3", fingering: "O-T | O X O | O O O", alternates: [] },
        { note: "C4", fingering: "O-T | O O O | O O O", alternates: [] },
        { note: "C#4/Db4", fingering: "O-O | X X X | X X X", alternates: [] },
        { note: "D4", fingering: "O-O | X X X | X X O", alternates: [] },
        { note: "D#4/Eb4", fingering: "O-O | X X X | X O O", alternates: [] },
        { note: "E4", fingering: "O-O | X X X | O O O", alternates: [] },
        { note: "F4", fingering: "O-O | X X O | O O O", alternates: [] },
        { note: "F#4/Gb4", fingering: "O-O | X O O | O O O", alternates: [] },
        { note: "G4", fingering: "R-T | X X X | X X X", alternates: [] },
        { note: "G#4/Ab4", fingering: "R-T | X X X | X X O", alternates: [] },
        { note: "A4", fingering: "R-T | X X X | X O O", alternates: [] },
        { note: "A#4/Bb4", fingering: "R-T | X X X | O O O", alternates: [] },
        { note: "B4", fingering: "R-T | X X O | O O O", alternates: [] },
        { note: "C5", fingering: "R-T | X O O | O O O", alternates: [] },
        { note: "C#5/Db5", fingering: "R-T | O O O | O O O", alternates: [] },
        { note: "D5", fingering: "R-O | X X X | X X X", alternates: [] },
        { note: "D#5/Eb5", fingering: "R-O | X X X | X X O", alternates: [] },
        { note: "E5", fingering: "R-O | X X X | X O O", alternates: [] },
        { note: "F5", fingering: "R-O | X X X | O O O", alternates: [] },
        { note: "F#5/Gb5", fingering: "R-O | X X O | O O O", alternates: [] },
        { note: "G5", fingering: "R-O | X O O | O O O", alternates: [] },
    ],
  },
  
  // ========== BASS CLARINET ==========
  {
    name: "Bass Clarinet",
    category: "Woodwind",
    notation_key: "X = Covered, O = Open, T = LH thumb hole, R = Register key. Low keys assumed.",
    hands_layout: ["Keys/Thumb", "Left Hand", "Right Hand", "Low Keys"],
    care_and_technique: [
        { title: "Gentle Assembly", description: "Assemble the bass clarinet carefully, especially when connecting the bell and the neck, to avoid bending keys. Use cork grease as needed." },
        { title: "Use the Peg", description: "Adjust the floor peg so the mouthpiece comes to you comfortably without needing to hunch over or reach up. This helps with posture and breath support." },
        { title: "Swab Both Sections", description: "Because of its size, you'll need to swab the top and bottom sections separately. Make sure to remove all moisture to protect the pads." },
    ],
    notes: [
        { note: "D3", fingering: "O-T | X X X | X X X | D", alternates: [] },
        { note: "D#3/Eb3", fingering: "O-T | X X X | X X X | Eb", alternates: [] },
        { note: "E3", fingering: "O-T | X X X | X X X", alternates: [] },
        { note: "F3", fingering: "O-T | X X X | X X O", alternates: [] },
        { note: "F#3/Gb3", fingering: "O-T | X X X | X O O", alternates: [] },
        { note: "G3", fingering: "O-T | X X X | O O O", alternates: [] },
        { note: "G#3/Ab3", fingering: "O-T | X X O | X X X", alternates: [] },
        { note: "A3", fingering: "O-T | X X O | O O O", alternates: [] },
        { note: "A#3/Bb3", fingering: "O-T | X O O | O O O", alternates: [] },
        { note: "B3", fingering: "O-T | O X O | O O O", alternates: [] },
        { note: "C4", fingering: "O-T | O O O | O O O", alternates: [] },
        { note: "C#4/Db4", fingering: "O-O | X X X | X X X", alternates: [] },
        { note: "D4", fingering: "O-O | X X X | X X O", alternates: [] },
        { note: "D#4/Eb4", fingering: "O-O | X X X | X O O", alternates: [] },
        { note: "E4", fingering: "O-O | X X X | O O O", alternates: [] },
        { note: "F4", fingering: "O-O | X X O | O O O", alternates: [] },
        { note: "F#4/Gb4", fingering: "O-O | X O O | O O O", alternates: [] },
        { note: "G4", fingering: "R-T | X X X | X X X", alternates: [] },
        { note: "G#4/Ab4", fingering: "R-T | X X X | X X O", alternates: [] },
        { note: "A4", fingering: "R-T | X X X | X O O", alternates: [] },
        { note: "A#4/Bb4", fingering: "R-T | X X X | O O O", alternates: [] },
        { note: "B4", fingering: "R-T | X X O | O O O", alternates: [] },
        { note: "C5", fingering: "R-T | X O O | O O O", alternates: [] },
    ],
  },

  // ========== SAXOPHONE (ALTO/TENOR/BARI SHARED) ==========
  {
    name: "Alto Saxophone",
    category: "Woodwind",
    notation_key:
      "Same relative fingering across saxes (written). X = Pressed, O = Open. Groups: OCT | LH 1-3 | RH 1-3 | Pinky/Side.",
    hands_layout: ["Octave", "Left Hand", "Right Hand", "Pinky/Side"],
    care_and_technique: [
        { title: "Neck and Mouthpiece Cleaning", description: "Regularly clean the neck with a flexible brush and swab the mouthpiece after playing. This is crucial for hygiene and tone." },
        { title: "Proper Neck Strap Use", description: "Adjust your neck strap so the mouthpiece easily reaches your mouth with good posture. The strap should carry the weight, not your hands." },
        { title: "Octave Key Maintenance", description: "The octave key mechanism (on the neck and body) can be delicate. Be careful not to bend it, and ensure the pads are closing properly to avoid squeaks on high notes." },
    ],
    notes: [
      { note: "A#3/Bb3", fingering: "O | X O O | O O O | Bb", alternates: [] },
      { note: "B3", fingering: "O | X O O | O O O | O", alternates: [] },
      { note: "C4", fingering: "O | O X O | O O O | O", alternates: [] },
      { note: "C#4/Db4", fingering: "O | O O O | O O O | O", alternates: [] },
      { note: "D4", fingering: "O | X X X | X X X | Eb", alternates: [] },
      { note: "D#4/Eb4", fingering: "O | X X X | X X O | Eb", alternates: [] },
      { note: "E4", fingering: "O | X X X | X X O | O", alternates: [] },
      { note: "F4", fingering: "O | X X X | X O O | O", alternates: [] },
      { note: "F#4/Gb4", fingering: "O | X X X | O X O | O", alternates: [] },
      { note: "G4", fingering: "O | X X X | O O O | O", alternates: [] },
      { note: "G#4/Ab4", fingering: "O | X X X | O O O | G#", alternates: [] },
      { note: "A4", fingering: "O | X X O | O O O | O", alternates: [] },
      { note: "A#4/Bb4", fingering: "O | X O O | O O O | O", alternates: ["O | X O X | O O O | O"] },
      { note: "B4", fingering: "OCT | X O O | O O O | O", alternates: [] },
      { note: "C5", fingering: "OCT | O X O | O O O | O", alternates: [] },
    ],
  },
  {
    name: "Tenor Saxophone",
    category: "Woodwind",
    notation_key:
      "Same relative fingering across saxes (written). X = Pressed, O = Open. Groups: OCT | LH 1-3 | RH 1-3 | Pinky/Side.",
    hands_layout: ["Octave", "Left Hand", "Right Hand", "Pinky/Side"],
    care_and_technique: [
        { title: "Neck and Mouthpiece Cleaning", description: "Regularly clean the neck with a flexible brush and swab the mouthpiece after playing. This is crucial for hygiene and tone." },
        { title: "Proper Neck Strap Use", description: "Adjust your neck strap so the mouthpiece easily reaches your mouth with good posture. The strap should carry the weight, not your hands." },
        { title: "Octave Key Maintenance", description: "The octave key mechanism (on the neck and body) can be delicate. Be careful not to bend it, and ensure the pads are closing properly to avoid squeaks on high notes." },
    ],
    notes: [
      { note: "A#3/Bb3", fingering: "O | X O O | O O O | Bb", alternates: [] },
      { note: "B3", fingering: "O | X O O | O O O | O", alternates: [] },
      { note: "C4", fingering: "O | O X O | O O O | O", alternates: [] },
      { note: "C#4/Db4", fingering: "O | O O O | O O O | O", alternates: [] },
      { note: "D4", fingering: "O | X X X | X X X | Eb", alternates: [] },
      { note: "D#4/Eb4", fingering: "O | X X X | X X O | Eb", alternates: [] },
      { note: "E4", fingering: "O | X X X | X X O | O", alternates: [] },
      { note: "F4", fingering: "O | X X X | X O O | O", alternates: [] },
      { note: "F#4/Gb4", fingering: "O | X X X | O X O | O", alternates: [] },
      { note: "G4", fingering: "O | X X X | O O O | O", alternates: [] },
      { note: "G#4/Ab4", fingering: "O | X X X | O O O | G#", alternates: [] },
      { note: "A4", fingering: "O | X X O | O O O | O", alternates: [] },
      { note: "A#4/Bb4", fingering: "O | X O O | O O O | O", alternates: ["O | X O X | O O O | O"] },
      { note: "B4", fingering: "OCT | X O O | O O O | O", alternates: [] },
      { note: "C5", fingering: "OCT | O X O | O O O | O", alternates: [] },
    ],
  },
  {
    name: "Baritone Saxophone",
    category: "Woodwind",
    notation_key:
      "Same relative fingering across saxes (written). X = Pressed, O = Open. Groups: OCT | LH 1-3 | RH 1-3 | Pinky/Side.",
    hands_layout: ["Octave", "Left Hand", "Right Hand", "Pinky/Side"],
    care_and_technique: [
        { title: "Neck and Mouthpiece Cleaning", description: "Regularly clean the neck with a flexible brush and swab the mouthpiece after playing. This is crucial for hygiene and tone." },
        { title: "Proper Neck Strap Use", description: "Adjust your neck strap so the mouthpiece easily reaches your mouth with good posture. The strap should carry the weight, not your hands." },
        { title: "Octave Key Maintenance", description: "The octave key mechanism (on the neck and body) can be delicate. Be careful not to bend it, and ensure the pads are closing properly to avoid squeaks on high notes." },
    ],
    notes: [
      { note: "A#3/Bb3", fingering: "O | X O O | O O O | Bb", alternates: [] },
      { note: "B3", fingering: "O | X O O | O O O | O", alternates: [] },
      { note: "C4", fingering: "O | O X O | O O O | O", alternates: [] },
      { note: "C#4/Db4", fingering: "O | O O O | O O O | O", alternates: [] },
      { note: "D4", fingering: "O | X X X | X X X | Eb", alternates: [] },
      { note: "D#4/Eb4", fingering: "O | X X X | X X O | Eb", alternates: [] },
      { note: "E4", fingering: "O | X X X | X X O | O", alternates: [] },
      { note: "F4", fingering: "O | X X X | X O O | O", alternates: [] },
      { note: "F#4/Gb4", fingering: "O | X X X | O X O | O", alternates: [] },
      { note: "G4", fingering: "O | X X X | O O O | O", alternates: [] },
      { note: "G#4/Ab4", fingering: "O | X X X | O O O | G#", alternates: [] },
      { note: "A4", fingering: "O | X X O | O O O | O", alternates: [] },
      { note: "A#4/Bb4", fingering: "O | X O O | O O O | O", alternates: ["O | X O X | O O O | O"] },
      { note: "B4", fingering: "OCT | X O O | O O O | O", alternates: [] },
      { note: "C5", fingering: "OCT | O X O | O O O | O", alternates: [] },
    ],
  },

  // ========== TRUMPET / CORNET (W22TP) ==========
  {
    name: "Trumpet",
    category: "Brass (Valves)",
    notation_key:
      "Numbers = valves to press. 0 = open. Alternates shown for intonation/passages.",
    care_and_technique: [
        { title: "Oiling Valves", description: "Apply a few drops of high-quality valve oil to each valve every day or two. Press the valve down, unscrew it, pull it out halfway, apply oil, then work it in." },
        { title: "Mouthpiece Buzzing", description: "Warm up by buzzing simple tunes on just the mouthpiece. This helps develop a strong and consistent embouchure for better tone and range." },
        { title: "Empty Water Keys", description: "Frequently empty your water keys (spit valves) to prevent gurgling sounds and to keep the inside of the instrument clean." },
    ],
    notes: [
      { note: "F#3/Gb3", fingering: "123", alternates: [] },
      { note: "G3", fingering: "13", alternates: [] },
      { note: "G#3/Ab3", fingering: "23", alternates: [] },
      { note: "A3", fingering: "12", alternates: [] },
      { note: "A#3/Bb3", fingering: "1", alternates: [] },
      { note: "B3", fingering: "2", alternates: [] },
      { note: "C4", fingering: "0", alternates: [] },
      { note: "C#4/Db4", fingering: "123", alternates: [] },
      { note: "D4", fingering: "13", alternates: [] },
      { note: "D#4/Eb4", fingering: "23", alternates: [] },
      { note: "E4", fingering: "12", alternates: [] },
      { note: "F4", fingering: "1", alternates: [] },
      { note: "F#4/Gb4", fingering: "2", alternates: ["3"] },
      { note: "G4", fingering: "0", alternates: ["13"] },
      { note: "G#4/Ab4", fingering: "23", alternates: [] },
      { note: "A4", fingering: "12", alternates: ["3"] },
      { note: "A#4/Bb4", fingering: "1", alternates: [] },
      { note: "B4", fingering: "2", alternates: [] },
      { note: "C5", fingering: "0", alternates: [] },
      { note: "C#5/Db5", fingering: "12", alternates: [] },
      { note: "D5", fingering: "1", alternates: [] },
      { note: "D#5/Eb5", fingering: "2", alternates: [] },
      { note: "E5", fingering: "0", alternates: [] },
      { note: "F5", fingering: "1", alternates: [] },
      { note: "F#5/Gb5", fingering: "2", alternates: [] },
      { note: "G5", fingering: "0", alternates: ["13"] },
    ],
  },
  
  // ========== TROMBONE (W21TB) ==========
  {
    name: "Trombone",
    category: "Brass (Slide)",
    notation_key:
      "Position number. 1 = shortest, 7 = longest. Adjust by ear/tuner.",
    care_and_technique: [
        { title: "Slide Lubrication", description: "A smooth slide is essential. Use a high-quality slide cream/lubricant and a spray bottle of water for the best action. Reapply as needed." },
        { title: "Protect the Slide", description: "The hand slide is very fragile. Never set the trombone down on the slide. Always use the slide lock when not playing to prevent it from falling." },
        { title: "Legato Tonguing", description: "Practice 'doo' or 'loo' tonguing (legato tonguing) to play smooth, connected notes without a harsh attack, especially in lyrical passages." },
    ],
    notes: [
      { note: "E2", fingering: "7", alternates: [] },
      { note: "F2", fingering: "6", alternates: [] },
      { note: "F#2/Gb2", fingering: "5", alternates: [] },
      { note: "G2", fingering: "4", alternates: [] },
      { note: "G#2/Ab2", fingering: "3", alternates: [] },
      { note: "A2", fingering: "2", alternates: [] },
      { note: "A#2/Bb2", fingering: "1", alternates: [] },
      { note: "B2", fingering: "7", alternates: [] },
      { note: "C3", fingering: "6", alternates: [] },
      { note: "C#3/Db3", fingering: "5", alternates: [] },
      { note: "D3", fingering: "4", alternates: [] },
      { note: "D#3/Eb3", fingering: "3", alternates: [] },
      { note: "E3", fingering: "2", alternates: [] },
      { note: "F3", fingering: "1", alternates: ["6"] },
      { note: "F#3/Gb3", fingering: "5", alternates: [] },
      { note: "G3", fingering: "4", alternates: [] },
      { note: "G#3/Ab3", fingering: "3", alternates: ["2 or 6"] },
      { note: "A3", fingering: "2", alternates: [] },
      { note: "A#3/Bb3", fingering: "1", alternates: [] },
      { note: "B3", fingering: "4", alternates: [] },
      { note: "C4", fingering: "3", alternates: [] },
      { note: "C#4/Db4", fingering: "2", alternates: ["1 or -4"] },
      { note: "D4", fingering: "1", alternates: ["4"] },
      { note: "D#4/Eb4", fingering: "3", alternates: [] },
      { note: "E4", fingering: "2", alternates: [] },
      { note: "F4", fingering: "1", alternates: [] },
    ],
  },

  // ========== F/B♭ HORN (W61HF) - CORRECTED ==========
  {
    name: "French Horn",
    category: "Brass (Valves)",
    notation_key: "F side valves shown. 0 = open. B♭ horn fingerings are shown in parenthesis, e.g., (T2). 'T' means thumb key.",
    care_and_technique: [
        { title: "Oiling Rotary Valves", description: "Rotary valves need both bearing oil (on the top and bottom of the rotor shaft) and spindle oil (on the linkage). Use rotor oil down the leadpipe for internal lubrication." },
        { title: "Right Hand Position", description: "Place your right hand inside the bell, cupped as if holding water, against the far side. This position is crucial for the horn's characteristic tone and helps with fine-tuning notes." },
        { title: "Emptying Water", description: "Horns collect a lot of condensation. Learn which slides to pull and how to rotate the horn to empty all the water effectively. It gathers in more places than you'd think!" },
    ],
    notes: [
        { note: "F#3/Gb3", fingering: "2", alternates: ["(T12)"] },
        { note: "G3", fingering: "0", alternates: ["(T1)"] },
        { note: "G#3/Ab3", fingering: "23", alternates: ["(T2)"] },
        { note: "A3", fingering: "12", alternates: ["(T0)"] },
        { note: "A#3/Bb3", fingering: "1", alternates: ["(T1)"] },
        { note: "B3", fingering: "2", alternates: ["(T2)"] },
        { note: "C4", fingering: "0", alternates: ["(T0)"] },
        { note: "C#4/Db4", fingering: "23", alternates: ["(T23)"] },
        { note: "D4", fingering: "1", alternates: ["(T12)"] },
        { note: "D#4/Eb4", fingering: "2", alternates: ["(T1)"] },
        { note: "E4", fingering: "0", alternates: ["(T2)"] },
        { note: "F4", fingering: "1", alternates: ["(T0)"] },
        { note: "F#4/Gb4", fingering: "2", alternates: ["(T1)"] },
        { note: "G4", fingering: "0", alternates: ["(T0)"] },
        { note: "G#4/Ab4", fingering: "23", alternates: ["(T2)"] },
        { note: "A4", fingering: "12", alternates: ["(T12)"] },
        { note: "A#4/Bb4", fingering: "1", alternates: ["(T1)"] },
        { note: "B4", fingering: "2", alternates: ["(T2)"] },
        { note: "C5", fingering: "0", alternates: ["(T0)"] },
        { note: "C#5/Db5", fingering: "23", alternates: ["(T23)"] },
        { note: "D5", fingering: "1", alternates: ["(T1)"] },
        { note: "D#5/Eb5", fingering: "2", alternates: ["(T2)"] },
        { note: "E5", fingering: "0", alternates: ["(T0)"] },
        { note: "F5", fingering: "1", alternates: ["(T1)"] },
        { note: "F#5/Gb5", fingering: "2", alternates: ["(T2)"] },
        { note: "G5", fingering: "0", alternates: ["(T0)"] },
    ],
  },
  
  // ========== BARITONE / EUPHONIUM B.C. (W21BC) ==========
  {
    name: "Baritone/Euphonium",
    category: "Brass (Valves)",
    notation_key:
      "Bass Clef (B.C.) fingerings. Numbers = valves. 0 = open.",
    care_and_technique: [
        { title: "Valve Maintenance", description: "Just like a trumpet, oil your valves regularly. On larger instruments, they can get sluggish quickly. Make sure to press them straight down to avoid wear." },
        { title: "Massive Air Support", description: "These instruments require a large, steady column of air. Practice deep, relaxed breaths from your diaphragm to produce a full, rich tone, especially in the low register." },
        { title: "Cleaning the Leadpipe", description: "Use a flexible 'snake' brush to periodically clean the leadpipe, where buildup can significantly affect responsiveness and tone." },
    ],
    notes: [
      { note: "E2", fingering: "123", alternates: [] },
      { note: "F2", fingering: "13", alternates: [] },
      { note: "F#2/Gb2", fingering: "23", alternates: [] },
      { note: "G2", fingering: "12", alternates: [] },
      { note: "G#2/Ab2", fingering: "1", alternates: [] },
      { note: "A2", fingering: "2", alternates: [] },
      { note: "A#2/Bb2", fingering: "0", alternates: [] },
      { note: "B2", fingering: "2", alternates: [] },
      { note: "C3", fingering: "1", alternates: [] },
      { note: "C#3/Db3", fingering: "12", alternates: [] },
      { note: "D3", fingering: "0", alternates: [] },
      { note: "D#3/Eb3", fingering: "2", alternates: [] },
      { note: "E3", fingering: "1", alternates: [] },
      { note: "F3", fingering: "0", alternates: [] },
      { note: "F#3/Gb3", fingering: "2", alternates: [] },
      { note: "G3", fingering: "0", alternates: [] },
      { note: "G#3/Ab3", fingering: "23", alternates: [] },
      { note: "A3", fingering: "12", alternates: [] },
      { note: "A#3/Bb3", fingering: "1", alternates: [] },
      { note: "B3", fingering: "2", alternates: [] },
      { note: "C4", fingering: "0", alternates: [] },
    ],
  },
  
   // ========== BARITONE / EUPHONIUM T.C. (W61TC) ==========
  {
    name: "Baritone/Euphonium (T.C.)",
    category: "Brass (Valves)",
    notation_key:
      "Treble Clef (T.C.) fingerings. Numbers = valves. 0 = open.",
    care_and_technique: [
        { title: "Valve Maintenance", description: "Just like a trumpet, oil your valves regularly. On larger instruments, they can get sluggish quickly. Make sure to press them straight down to avoid wear." },
        { title: "Massive Air Support", description: "These instruments require a large, steady column of air. Practice deep, relaxed breaths from your diaphragm to produce a full, rich tone, especially in the low register." },
        { title: "Cleaning the Leadpipe", description: "Use a flexible 'snake' brush to periodically clean the leadpipe, where buildup can significantly affect responsiveness and tone." },
    ],
    notes: [
      { note: "F#3/Gb3", fingering: "123", alternates: [] },
      { note: "G3", fingering: "13", alternates: [] },
      { note: "G#3/Ab3", fingering: "23", alternates: [] },
      { note: "A3", fingering: "12", alternates: [] },
      { note: "A#3/Bb3", fingering: "1", alternates: [] },
      { note: "B3", fingering: "2", alternates: [] },
      { note: "C4", fingering: "0", alternates: [] },
      { note: "C#4/Db4", fingering: "123", alternates: [] },
      { note: "D4", fingering: "13", alternates: [] },
      { note: "D#4/Eb4", fingering: "23", alternates: [] },
      { note: "E4", fingering: "12", alternates: [] },
      { note: "F4", fingering: "1", alternates: [] },
      { note: "F#4/Gb4", fingering: "2", alternates: [] },
      { note: "G4", fingering: "0", alternates: [] },
      { note: "G#4/Ab4", fingering: "23", alternates: [] },
      { note: "A4", fingering: "12", alternates: [] },
      { note: "A#4/Bb4", fingering: "1", alternates: [] },
      { note: "B4", fingering: "2", alternates: [] },
      { note: "C5", fingering: "0", alternates: [] },
      { note: "C#5/Db5", fingering: "12", alternates: [] },
      { note: "D5", fingering: "1", alternates: [] },
      { note: "D#5/Eb5", fingering: "2", alternates: [] },
      { note: "E5", fingering: "0", alternates: [] },
    ],
  },

  // ========== TUBA (BB♭) - CORRECTED ==========
  {
    name: "Tuba",
    category: "Brass (Valves)",
    notation_key: "Numbers = valves. 0 = open. For a standard 3-valve BB♭ Tuba.",
    care_and_technique: [
        { title: "Valve Maintenance", description: "Oil your valves regularly with high-quality piston valve oil. On larger instruments, they can get sluggish quickly. Make sure to press them straight down to avoid wear." },
        { title: "Massive Air Support", description: "The tuba requires a large, steady column of air. Practice deep, relaxed breaths from your diaphragm to produce a full, rich tone, especially in the low register." },
        { title: "Transporting Safely", description: "Due to its size and weight, be careful when moving your tuba. Use a good case with wheels if possible, and be mindful of doorways and stairs to avoid dents." },
    ],
    notes: [
        { note: "F1", fingering: "13", alternates: [] },
        { note: "F#1/Gb1", fingering: "23", alternates: [] },
        { note: "G1", fingering: "12", alternates: [] },
        { note: "G#1/Ab1", fingering: "1", alternates: [] },
        { note: "A1", fingering: "2", alternates: [] },
        { note: "A#1/Bb1", fingering: "0", alternates: [] },
        { note: "B1", fingering: "2", alternates: ["123"] },
        { note: "C2", fingering: "1", alternates: ["13"] },
        { note: "C#2/Db2", fingering: "12", alternates: ["23"] },
        { note: "D2", fingering: "0", alternates: ["123"] },
        { note: "D#2/Eb2", fingering: "2", alternates: [] },
        { note: "E2", fingering: "1", alternates: [] },
        { note: "F2", fingering: "0", alternates: [] },
        { note: "F#2/Gb2", fingering: "2", alternates: [] },
        { note: "G2", fingering: "0", alternates: ["12"] },
        { note: "G#2/Ab2", fingering: "23", alternates: [] },
        { note: "A2", fingering: "12", alternates: [] },
        { note: "A#2/Bb2", fingering: "1", alternates: [] },
        { note: "B2", fingering: "2", alternates: [] },
        { note: "C3", fingering: "0", alternates: [] },
        { note: "C#3/Db3", fingering: "12", alternates: [] },
        { note: "D3", fingering: "1", alternates: [] },
        { note: "D#3/Eb3", fingering: "2", alternates: [] },
        { note: "E3", fingering: "1", alternates: ["0"] },
        { note: "F3", fingering: "0", alternates: [] },
    ],
  },

  // ========== PERCUSSION ==========
  {
    name: "Percussion",
    category: "Percussion",
    notation_key: "Percussion covers many instruments (snare, mallets, timpani). Fingering charts do not apply. Focus on rudiments, stickings (R/L), and technique for each specific instrument.",
    hands_layout: [],
    care_and_technique: [
        { title: "Practice Pad is Key", description: "Most of your practice time, especially on fundamentals like rudiments, should be on a practice pad to build muscle memory without creating a lot of noise." },
        { title: "Check Your Grip", description: "Whether using matched or traditional grip, ensure it's relaxed. A tight grip can limit speed and cause injury. Ask your director to check your form." },
        { title: "Tuning the Drums", description: "Learn the basics of tuning a snare drum and timpani. A well-tuned instrument sounds better and is more rewarding to play." },
    ],
    notes: [], // Fingering charts are not applicable for general percussion
  },
  
  // ========== PIANO ==========
  {
    name: "Piano",
    category: "Keyboard",
    notation_key: "Piano fingerings are suggestions, not rules. Numbers 1-5 represent thumb through pinky finger on each hand. Follow fingerings in your music to learn efficient technique.",
    hands_layout: [],
    care_and_technique: [
        { title: "Keep it Clean", description: "Dust your piano keys regularly with a soft, dry cloth. For cleaning, use a slightly damp cloth and wipe front-to-back, not side-to-side." },
        { title: "Good Posture", description: "Sit centered on the bench at a distance where your elbows are slightly in front of your body. Your forearms should be parallel to the floor." },
        { title: "Hand Position", description: "Maintain a curved, natural hand shape, as if you were holding a ball. This allows for more control and less tension." },
    ],
    notes: [], // Piano fingerings are context-dependent and not listed here.
  }
];